from diagrams import Diagram, Cluster, Edge
from diagrams.azure.web import StaticApps, AppServices
from diagrams.azure.database import SQLDatabases
from diagrams.azure.security import KeyVaults
from diagrams.azure.identity import ActiveDirectory
from diagrams.azure.monitor import ApplicationInsights, LogAnalyticsWorkspaces
from diagrams.azure.storage import BlobStorage
from diagrams.onprem.client import Users

# Generated by design agent | 2026-02-26

graph_attr = {
    "nodesep": "0.8",
    "ranksep": "1.0",
    "splines": "ortho",
    "pad": "0.5",
}

with Diagram(
    "terraform-e2e design architecture",
    show=False,
    direction="LR",
    filename="agent-output/terraform-e2e/03-des-diagram",
    graph_attr=graph_attr,
):
    with Cluster("External") as clu_ext_users:
        n_edge_web_customer = Users("customers")
        n_id_entra_auth = ActiveDirectory("entra external id")

    with Cluster("Azure") as clu_sub_azure:
        with Cluster("westeurope") as clu_zone_westeurope:
            n_web_swa_frontend = StaticApps("static web app")

        with Cluster("swedencentral") as clu_zone_swedencentral:
            with Cluster("rg-terraform-e2e-dev") as clu_rg_terraform_e2e_dev:
                with Cluster("app tier") as clu_tier_app:
                    n_app_appservice_api = AppServices("app service b1")

                with Cluster("data tier") as clu_tier_data:
                    n_data_sql_primary = SQLDatabases("azure sql basic")

                with Cluster("sec tier") as clu_tier_sec:
                    n_sec_kv_secrets = KeyVaults("key vault")

                with Cluster("ops tier") as clu_tier_ops:
                    n_ops_appi_telemetry = ApplicationInsights("app insights")
                    n_ops_loga_workspace = LogAnalyticsWorkspaces("log analytics")

                with Cluster("state tier") as clu_tier_state:
                    n_ops_blob_tfstate = BlobStorage("state backend")

    n_edge_web_customer >> Edge(label="request") >> n_web_swa_frontend
    n_edge_web_customer >> Edge(label="auth", color="darkgreen") >> n_id_entra_auth
    n_web_swa_frontend >> Edge(label="request") >> n_app_appservice_api

    n_app_appservice_api >> Edge(label="read") >> n_data_sql_primary
    n_app_appservice_api >> Edge(label="write") >> n_data_sql_primary
    n_app_appservice_api >> Edge(label="secret", color="darkgreen") >> n_sec_kv_secrets

    n_app_appservice_api >> Edge(label="telemetry", style="dashed", color="dimgray") >> n_ops_appi_telemetry
    n_ops_appi_telemetry >> Edge(label="telemetry", style="dashed", color="dimgray") >> n_ops_loga_workspace
    n_data_sql_primary >> Edge(label="telemetry", style="dashed", color="dimgray") >> n_ops_loga_workspace
    n_sec_kv_secrets >> Edge(label="telemetry", style="dashed", color="dimgray") >> n_ops_loga_workspace
    n_ops_blob_tfstate >> Edge(label="admin", color="darkgreen") >> n_ops_loga_workspace
